// Theirs
import type { PropsWithChildren } from "react";
import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";

// Ours
import { Header } from "@/components/Header";
import { Label } from "@/constants";
import "./globals.css";


const geistMono = Geist_Mono({
  subsets: ["latin"],
  display: "swap",
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.className}`}
        data-wrap
      >
        <Header heading={Label.HEADING} />
        <main>{children}</main>
        <footer>
          <h3>Footer</h3>
        </footer>
      </body>
    </html>
  );
}
